version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - db:/var/lib/test/postgresql/data

volumes:
  db:
